name: Prettier Formatter

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Prettier + Svelte plugin
        run: npm install --no-save prettier prettier-plugin-svelte

      - name: Run Prettier
        run: npx prettier --write "**/*.{js,ts,tsx,jsx,svelte,css,scss,md,json,yaml,yml,html}"