name: Prettier Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install --no-save --legacy-peer-deps prettier prettier-plugin-svelte

      - name: Run Prettier Check
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --check "**/*.{js,ts,tsx,jsx,svelte,css,scss,md,json,html}" --ignore-path .prettierignore
